//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public bool Receita { get; set; }
        public decimal Valor { get; set; }
        public int IdTipoTransacao { get; set; }
    
        public virtual TipoTransacao TipoTransacao { get; set; }
    }
}
