//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string NotaFiscal { get; set; }
        public decimal ValorTotal { get; set; }
        public int IdCliente { get; set; }
        public int IdFormaPagamento { get; set; }
        public int IdFuncionario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
